### ISSUE TITLE
P3P template displays inaccurate data

### ISSUE THREAD

**Issue by AugmentedAntics** [TGEnigma/010-Editor-Templates#21]
A couple of issues regarding what is shown:

1. EXP and money dropped from enemies is listed in a seemingly flipped order (EXP drops are listed as money, and enemies don't actually drop money).
2. Elemental affinity data is totally inaccurate. It lists physical affinities from P3, but ailment affinities from P4. None of the data seems to match any Persona or enemy in the game.
3. Actual skill ailments are pushed down by 1 from where it should be (charm is distress, poison is unconscious member status, etc.).

**Comment by Phoenix-neat** [comment]
I'll take a look at it, thank you.

For 3) at least, they added Dizzy to Portable so I likely just have to add it

**Comment by TGEnigma** [comment]
Has this been fixed?

**Comment by Phoenix-neat** [comment]
No, I'll take another look at it. I fixed the elemental affinities for FES I can port over the changes when I push my template

**Comment by Phoenix-neat** [comment]
ok it took uh

6 months

but I did it
