### ISSUE TITLE
p4g_tbl.bt Shows Nonsense

### ISSUE THREAD

**Issue by MasterDriverRex** [TGEnigma/010-Editor-Templates#25]
I want to edit a couple skills and Personas in Persona 4 Golden, so I extracted /data_e/init_free.bin/battle/SKILL.TBL and PERSONA.TBL using Amicitia v1.9.5. Opened them up in 010 Editor, everything looks good so far.

Then I ran the p4g_tbl.bt template, hoping it would clearly break the combined mess of hexadecimal into easy-to-read (and edit) blocks for each skill/Persona. Except it doesn't. As should hopefully be seen in the attached screenshots, the template just lists a whole lot of size 1h bytes and utterly fails to clear anything up.

Is there a way to fix this, so I can - for example - change Izanagi-no-Okami's resistances into absorptions, edit what skills he gets via level-up, and lower the HP cost of Primal Force?  

![p4g_tbl bt doesn't work as expected](https://user-images.githubusercontent.com/53700965/112111796-cd7bc600-8c08-11eb-9433-f479e122c81c.png)
![p4g_tbl bt doesn't work as expected2](https://user-images.githubusercontent.com/53700965/112111804-cfde2000-8c08-11eb-8e1f-a1f7594196e6.png)

**Comment by TGEnigma** [comment]
The template relies on the file name to determine the contents of the file. If you rename the file back to its original name (in this case SKILL.TBL), it should work as expected.
